LMS.Web/Models/CatagoryModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Web.Models
{
    public class CatagoryModel
    {

        [Key]
        public Guid category_id { get; set; }
        [Required(ErrorMessage = "Catagory Title is required.")]
        public string title { get; set; }
        [Required(ErrorMessage = "Catagory Type is required.")]
        public string type { get; set; }
        public virtual IEnumerable<CourseModel> course { get; set; }


    }
}

LMS.Web/Models/CourseModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Web.Models
{
    public class CourseModel
    {
        [Key]
        public int courseId { get; set; }
        public string title { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string author { get; set; }
        public bool status { get; set; }
        public DateTime createdDate { get; set; }
        public virtual IEnumerable<UnitsModel> units { get; set; }

    }
}

LMS.Web/Models/ErrorViewModel.cs
using System;

namespace LMS.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LMS.Web/Models/UnitsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Web.Models
{
    public class UnitsModel
    {
    }
}

LMS.Web/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Web.Models
{
    public class UserModel
    {
        public Guid userId { get; set; }
        [Required(ErrorMessage = "username is required.")]
        public string username { get; set; }
        public string useremail { get; set; }
        [Required(ErrorMessage = "password is required.")]
        public string password { get; set; }
        public DateTime createdDate { get; set; }
        public bool status { get; set; }
    }
}

LMS.Web/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LMS.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using LMS.Service;
using LMS.Data.Models;

namespace LMS.Web.Controllers
{
    public class CatalogController : Controller
    {

        private readonly ICategoriesServices _categoriesServices;

        public CatalogController(ICategoriesServices categoriesServices)
        {
            _categoriesServices = categoriesServices;

        }

        public IActionResult Index()
        {
            IEnumerable<CatagoryModel> listCatagorydto = Mapper.Map<IEnumerable<categories>, IEnumerable<CatagoryModel>>(_categoriesServices.getAllCategories());
            return View(listCatagorydto);
        }

       
        public IActionResult CreateCatalog(CatagoryModel catagory)
        {
            if (ModelState.IsValid)
            {
                catagory.category_id = Guid.NewGuid();
                categories catagorydto = Mapper.Map<CatagoryModel, categories>(catagory);
                _categoriesServices.createCategories(catagorydto);
                ViewBag.Message = catagory.title + "Successfully Registered.";
            }
            return View();
        }


        public IActionResult GetResult()
        {
            IEnumerable<CatagoryModel> listCatagorydto = Mapper.Map<IEnumerable<categories>, IEnumerable<CatagoryModel>>(_categoriesServices.getAllCategories());
            return View(listCatagorydto);
        }

    }
}

LMS.Web/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace LMS.Web.Controllers
{
    public class CourseController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LMS.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LMS.Web.Models;
using LMS.Data;
using Microsoft.AspNetCore.Http;
using AutoMapper;
using LMS.Data.Models;
using LMS.Service;

namespace LMS.Web.Controllers
{
    public class HomeController : Controller
    {

        private readonly IUserServices _userServices;

        public HomeController(IUserServices userServices)
        {
            _userServices = userServices;

        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(UserModel userAccount)
        {
            if (ModelState.IsValid)
            {
                userAccount.userId = Guid.NewGuid();
                userAccount.createdDate = DateTime.Now;
                userAccount.status = true;
                users userdto = Mapper.Map<UserModel, users>(userAccount);
                _userServices.Add(userdto);
                ViewBag.Message = userAccount.username + "Successfully Registered.";
            }
            return View();
        }


        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(UserModel userAccount)
        {
           
            if (ModelState.IsValid)
            {
                users userdto = AutoMapper.Mapper.Map<UserModel, users>(userAccount);
                var user = _userServices.Login(userdto);
                if (user != null)
                {
                    if (user.password == user.password)
                    {
                        HttpContext.Session.SetString("userID", user.userId.ToString());
                        HttpContext.Session.SetString("username", user.username.ToString());
                        ViewBag.Message = "Welcome Registered.";
                    }
                    else
                    ModelState.AddModelError("", "Password is wrong.");
                }
                else
                {
                    ModelState.AddModelError("", "username or password is wrong.");
                }

            }
            return View();
        }


        public ActionResult Welcome()
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("userID")))
            {
                return View();
            }
            else
            {
                return RedirectToAction("login");
            }

        }

        public ActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");

        }




        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LMS.Web/Controllers/ScoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace LMS.Web.Controllers
{
    public class ScoreController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LMS.Web/Views/Catalog/Index.cshtml
@model IEnumerable<LMS.Web.Models.CatagoryModel>

@{
    ViewData["Title"] = "createCatalog";
}

<h2>createCatalog</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.category_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.type)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.category_id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.type)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>

LMS.Web/Views/Catalog/createCatalog.cshtml
@model IEnumerable<LMS.Web.Models.CatagoryModel>

@{
    ViewData["Title"] = "createCatalog";
}

<h2>createCatalog</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.category_id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.type)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.category_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.type)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

LMS.Web/Views/Course/Course.cshtml
@{
    ViewData["Title"] = "Course";
}

<h2>Course List</h2>

LMS.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LMS.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
<h3>Welcome to SmartLmS</h3>
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--4-col">
        <div class="demo-card-square mdl-card mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand" id="catalog">
                <h2 class="mdl-card__title-text homeLabel">Catalog</h2>
            </div>
            <div class="mdl-card__supporting-text">
                
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored" asp-controller="Catalog" asp-action="Index">
                    View Catalog
                </a>
            </div>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--4-col">
        <div class="demo-card-square mdl-card mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand" id="courses">
                <h2 class="mdl-card__title-text homeLabel">Courses</h2>
            </div>
            <div class="mdl-card__supporting-text">
               
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored" asp-controller="Course" asp-action="Index">
                    View Course Index
                </a>
            </div>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--4-col">
        <div class="demo-card-square mdl-card mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand" id="Scores">
                <h2 class="mdl-card__title-text homeLabel">Scores</h2>
            </div>
            <div class="mdl-card__supporting-text">
               
            </div>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored" asp-controller="Score" asp-action="Index">
                    View Score Index
                </a>
            </div>
        </div>
    </div>
</div>

LMS.Web/Views/Home/Login.cshtml
@model UserModel
@{
    ViewData["Title"] = "login";
}


<form class="form-horizontal" asp-controller="Home" asp-action="Login" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="username" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="username" class="form-control" />
            <span asp-validation-for="username" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="password" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="password" class="form-control" />
            <span asp-validation-for="password" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Login</button>
        </div>
    </div>
</form>

LMS.Web/Views/Home/Register.cshtml
@model UserModel
@{
    ViewData["Title"] = "Register";
}

<h2>Register</h2>

<div class="form-horizontal">
    <form asp-controller="Home" asp-action="Register" method="post">
        @if (ViewBag.Message != null)
        {
            <div class="form-control">
                <div class="col-md-10">@ViewBag.Message</div>
            </div>
        }


        <div class="form-group">
            <label asp-for="username" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="username" class="form-control" />
                <span asp-validation-for="username" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="password" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="password" class="form-control" />
                <span asp-validation-for="password" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="useremail" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="useremail" class="form-control" />
                <span asp-validation-for="useremail" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-default">Register</button>
            </div>
        </div>
    </form>
</div>

LMS.Web/Views/Score/Score.cshtml
@{
    ViewData["Title"] = "Score";
}

<h2>Scores</h2>

LMS.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Smart Library Management System</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" />
    <link href=”//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css” rel=”stylesheet”>
    <link href="https://fonts.googleapis.com/css?family=Coda" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

</head>
<body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="custom-header mdl-layout__header mdl-layout__header--waterfall">
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <span class="mdl-layout-title logo"><a href="/">Smart LMS</a></span>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation. We hide it in small screens. -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="mdl-navigation__link" asp-controller="Home" asp-action="Contact">Contact</a>
                    

                    @if (Context.Session.GetString("userID") != null)
                    {
                        <a class="mdl-navigation__link" herf="#">@Context.Session.GetString("username")</a>
                        <a class="mdl-navigation__link" asp-controller="Home" asp-action="Logout">Logout</a>
                    }
                    else
                    {
                        <a class="mdl-navigation__link" asp-controller="Home" asp-action="Register">Register</a>
                        <a class="mdl-navigation__link" asp-controller="Home" asp-action="Login">Login</a>
                    }
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">LightLib</span>
            <nav class="mdl-navigation">
                <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                <a class="mdl-navigation__link" asp-controller="Catalog" asp-action="Index">Catalog</a>
            </nav>
        </div>
        <div class="page-content">

            @RenderBody()
        </div>
    </div>
    @RenderSection("Styles", required: false)
    @RenderSection("Scripts", required: false)
    <script src="https://use.fontawesome.com/6110b02b27.js"></script>
</body>
</html>